"""Add Empresa table

Revision ID: 18cb9202368b
Revises: 9c26a26221f5
Create Date: 2025-10-29 18:57:55.950300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cb9202368b'
down_revision = '9c26a26221f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('billing_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_billing_status'), ['billing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresa_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresa_nome'), ['nome'], unique=True)
        batch_op.create_index(batch_op.f('ix_empresa_plan_tier'), ['plan_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresa_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_updated_at'))
        batch_op.drop_index(batch_op.f('ix_empresa_plan_tier'))
        batch_op.drop_index(batch_op.f('ix_empresa_nome'))
        batch_op.drop_index(batch_op.f('ix_empresa_created_at'))
        batch_op.drop_index(batch_op.f('ix_empresa_billing_status'))

    op.drop_table('empresa')
    # ### end Alembic commands ###
