"""Add device and session fields to User

Revision ID: 55a1b2947f89
Revises: 
Create Date: 2025-10-29 17:52:35.935803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55a1b2947f89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupom', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('data_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_fingerprint', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('device_last_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active_session_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('active_session_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_active_session_id'), ['active_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_device_fingerprint'), ['device_fingerprint'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_user_active_session_id'))
        batch_op.drop_column('active_session_updated_at')
        batch_op.drop_column('active_session_id')
        batch_op.drop_column('device_last_updated')
        batch_op.drop_column('device_fingerprint')

    with op.batch_alter_table('cupom', schema=None) as batch_op:
        batch_op.alter_column('data_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('data_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
