"""Add plan_tier to UserSettings

Revision ID: 9c26a26221f5
Revises: 55a1b2947f89
Create Date: 2025-10-29 18:04:44.220334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c26a26221f5'
down_revision = '55a1b2947f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_tier', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_settings_plan_tier'), ['plan_tier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_plan_tier'))
        batch_op.drop_column('plan_tier')

    # ### end Alembic commands ###
