"""Add empresa_id FK to User

Revision ID: ba2871b5f4db
Revises: 18cb9202368b
Create Date: 2025-10-29 19:06:49.262772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2871b5f4db'
down_revision = '18cb9202368b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_empresa_id'))
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
