"""Add AuditLog table

Revision ID: f30069d0c0c3
Revises: ba2871b5f4db
Create Date: 2025-10-29 19:41:07.999120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30069d0c0c3'
down_revision = 'ba2871b5f4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=30), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entidade_id'), ['entidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entidade_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entidade'))
        batch_op.drop_index(batch_op.f('ix_audit_log_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_acao'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
